[package]
name = "cdt_tablet"
version = "0.1.0"
authors = ["clay53 <clayton@claytondoesthings.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.5"